
cloud:
  aws:
    credentials:
      access-key: AKIAUCYWUROEICTPI7GH
      secret-key: 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
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: springeventmanager


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 5432